services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  backend:
    build:
      context: ./react-aws-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    # volumes:
    #   - ./react-aws-server:/app
    networks:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./react-aws-server
          target: /app
    env_file:
      - .env

  frontend:
    build:
      context: ./react-aws
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./react-aws/src:/app/src
      # - node_modules:/app/node_modules
    networks:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./react-aws
          target: /app
networks:
  db:
    driver: bridge

volumes:
  node_modules:
